events {}

http {
    upstream fastapi_backend {
        server fastapi:8000;
    }


    server {
        listen 80;
        server_name ds-barbershop.ru www.ds_barbershop.ru;
        return 301 https://$host$request_uri;

    }




    server {
        listen 443 ssl;
        server_name ds-barbsershop.ru www.ds-barbershop.ru;

        ssl_certificate /etc/letsencrypt/live/ds-barbershop.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/ds-barbershop.ru/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;


        location / {
            proxy_pass http://fastapi_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded-for;
            proxy_set_header Proto $scheme;


            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }

        

    }
}