events {}

http {
    upstream fastapi_backend {
        server fastapi:8000;
    }


    server {
        listen 80;
        server_name ds-barbershop.ru www.ds_barbershop.ru;
        return 301 https://$host$request_uri;

    }




    server {
        listen 443 ssl;
        server_name ds-barbsershop.ru www.ds-barbershop.ru;

        ssl_certificate /etc/letsencrypt/live/ds-barbershop.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/ds-barbershop.ru/privkey.pem;



        location / {
            proxy_pass http://fastapi_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded-for;
            proxy_set_header Proto $scheme;
        }

    }
}